In [1]:
from leaderboard import ResultAggregator

result_aggregator = ResultAggregator(year = 2026, round_number=1)
aggregated_race_results, aggregated_sprint_results = result_aggregator.aggregate_results()
aggregated_race_results

Fetching data from: https://api.openf1.org/v1/sessions?year=2026
Fetching data from: https://api.openf1.org/v1/session_result?session_key=11234
Fetching data from: https://api.openf1.org/v1/drivers?
Fetching data from: https://api.openf1.org/v1/championship_drivers?session_key=11234
Fetching data from: https://api.openf1.org/v1/drivers?session_key=11234
No Sprint Race

   driver_number  position name_acronym  position_start
0             63       1.0          RUS             1.0
1             12       2.0          ANT             NaN
2             16       3.0          LEC             NaN
3             44       4.0          HAM             NaN
4              1       5.0          NOR             6.0
5              3       6.0          VER             NaN
6             87       7.0          BEA            12.0
7             41       8.0          LIN             9.0
8              5       9.0          BOR            10.0
9             10      10.0          GAS            14.0

In [2]:
from tips_reader import TipsReader
gp = TipsReader("7UogehrrK_Text_Melbourne GP_11_11.xlsx")
gp.df

,index,submitted_time,name,top_ten,dnf_picks,drivers_champ,constructors_champ,time_spent_s
0,1,2026-03-04 07:15:47,Antonio,"[RUS, NOR, VER, ANT, PIA, LEC, HAM, GAS, HAD, ...",NaN,RUS,Mercedes,222
1,2,2026-03-04 08:46:41,Rino,"[RUS, VER, LEC, HAM, ANT, NOR, PIA, HAD, GAS, ...",NaN,RUS,Mercedes,454
2,3,2026-03-04 14:27:01,Barry,"[PIA, VER, NOR, RUS, ANT, LEC, SAI, HAM, HAD, ...",[STR],PIA,McLaren,760
3,4,2026-03-04 15:48:02,Josh,"[VER, RUS, LEC, PIA, HAM, NOR, ANT, HAD, LAW, ...",[STR],LEC,McLaren,127
4,5,2026-03-05 17:45:29,Dean,"[RUS, NOR, PIA, VER, LEC, HAM, ANT, BEA, HAD, ...","[ALO, STR]",VER,McLaren,319
5,6,2026-03-05 17:49:51,Alex,"[NOR, VER, PIA, HAD, LEC, HAM, RUS, ANT, ALB, ...","[BOR, BOT, PER]",VER,Red Bull Racing,51
6,7,2026-03-05 19:25:40,Jake,"[RUS, LEC, VER, PIA, HAM, NOR, ANT, BEA, OCO, ...",NaN,RUS,Ferrari,289
7,8,2026-03-05 21:12:48,Luca,"[RUS, VER, NOR, LEC, PIA, ALB, ANT, HAM, HAD, ...","[ALO, STR]",VER,Mercedes,1041
8,9,2026-03-06 09:10:17,Riki,"[VER, RUS, NOR, PIA, LEC, ANT, HAM, SAI, OCO, ...",NaN,VER,Mercedes,159
9,10,2026-03-06 09:22:44,Tara,"[PIA, VER, NOR, RUS, LEC, ANT, ALO, HAD, HAM, ...",NaN,NOR,Mercedes,459
10,11,2026-03-06 19:00:17,Veljko,"[PIA, RUS, VER, NOR, LEC, ANT, HAM, HAD, SAI, ...",[LAW],VER,Mercedes,500